[package]
name = "tine-storage"
version = "0.6.3"
edition = "2021"
license = "AGPL-3.0-only"
authors = ["Martin Koutecký"]
description = "Physical persistence mechanisms for Tine"
repository = "https://github.com/martinkoutecky/tine-storage"
readme = "README.md"
publish = false

[features]
test-support = []

[dependencies]
cap-std = "4.0.2"
fs2 = "0.4.3"
postcard = { version = "1.1.3", features = ["alloc"] }
rusqlite = { version = "0.37.0", features = ["bundled", "functions"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10"
uuid = { version = "1", features = ["v4", "serde"] }

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[target.'cfg(windows)'.dependencies]
cap-fs-ext = "=4.0.2"
windows-sys = { version = "0.61.2", features = ["Win32_Foundation", "Win32_Storage_FileSystem"] }
